DROP RestArea CASCADE CONSTRAINTS;
DROP GasStation CASCADE CONSTRAINTS;
DROP FoodMenu CASCADE CONSTRAINTS;
DROP Post CASCADE CONSTRAINTS;
DROP Comment CASCADE CONSTRAINTS;
DROP RA_like CASCADE CONSTRAINTS;
DROP GS_like CASCADE CONSTRAINTS;
DROP FM_like CASCADE CONSTRAINTS;
DROP Post_like CASCADE CONSTRAINTS;

