UPDATE SCHEDULE SET 
			subject= 'hello2' , startdate='2020-12-10', enddate= '2020-12-10', memo= 'test'
WHERE subject = 'hello';

SELECT * FROM SCHEDULE s ;


SELECT 
UM_UID , UM_USERNAME, UM_NICKNAME, UM_REGDATE, UM_ENABLED
FROM usermember;

INSERT INTO USERMEMBER (UM_UID , UM_USERNAME, UM_PASSWORD, UM_NICKNAME, UM_REGDATE, UM_ENABLED)
VALUES (1,'hello','hello','hello', sysdate, 1);


SELECT count(*) FROM USERMEMBER u;


INSERT INTO userMember(um_uid, um_username, um_password ,um_nickname) VALUES(8, 'park', '$2a$10$5Yy/c52u4Ped7j11mMxKEeuHAIRHjiZyg5NyltWqpW5MGIh6zk/Ky', '박성언');


SELECT * FROM USERMEMBER u ;


	SELECT 
			UM_UID , UM_USERNAME, UM_NICKNAME, UM_REGDATE, UM_ENABLED
		FROM 
			(SELECT ROWNUM AS RNUM, T.* FROM
				(SELECT * FROM USERMEMBER ORDER BY UM_UID DESC) T)
	
				
				
SELECT * FROM USERMEMBER  WHERE UM_USERNAME = 'hello';
SELECT* FROM USERMEMBER  WHERE UM_NICKNAME = 'hello';


SELECT * FROM USERMEMBER u2 ;
SELECT 
	UM_NICKNAME, UM_ENABLED

SELECT * FROM post;
		
SELECT * FROM GASSTATION g ;

INSERT INTO POST 
(post_id, post_title, POST_CONTENTS, UM_UID, UM_USERNAME, POST_REGDATE, RA_CODE, POST_REPORTED)
VALUES
(14,'쿠죵','쿠죵',1, 'hello',sysdate, 'A00001','20')

SELECT* FROM post; 


	SELECT 
		 post_id , post_title, POST_CONTENTS, UM_UID, UM_USERNAME, POST_REGDATE, RA_CODE, POST_REPORTED
		FROM 
			(SELECT ROWNUM AS RNUM, T.* FROM
				(SELECT * FROM POST ORDER BY post_id DESC) T)
		WHERE
			RNUM >= #{from} AND RNUM < (#{from} + #{pagenationPage});
			
		SELECT * FROM post;
	
	
	

	SELECT 
		POST_REPORTED, POST_TITLE 
		FROM ( SELECT ROWNUM AS RNUM, T.* from 
				 (SELECT * FROM post ORDER BY POST_REPORTED desc)	T		)
		WHERE rnum >= 3 AND rnum <= 7;	
		
SELECT POST_REPORTED FROM post
WHERE ROWNUM <=5 ORDER BY POST_REPORTED;

SELECT
	  POST_REPORTED 
	FROM post
WHERE ROWNUM <= 100 ORDER BY POST_REPORTED;

SELECT POST_TITLE , POST_REPORTED FROM post 
WHERE ROWNUM <=5
ORDER BY post_id;


SELECT * FROM post 
WHERE POST_TITLE = '쿠잔' OR UM_USERNAME ='null';

SELECT * FROM POST WHERE UM_USERNAME = 'hello';
SELECT * FROM post WHERE POST_TITLE  = '쿠잔';
	
	SELECT POST_REPORTED, post_title
	FROM POST
	WHERE ROWNUM <=5
	ORDER BY POST_REPORTED DESC;

SELECT ROWNUM , POST_REPORTED FROM POST WHERE ROWNUM<=2;

SELECT * FROM POST;

SELECT ROWNUM, POST_ID ,POST_REPORTED  FROM 
(SELECT * FROM POST ORDER BY POST_ID DESC)
WHERE ROWNUM <=5;

